import type { RawEvent } from '../events/types.js'

export type Capability =
  | 'groups'
  | 'group_mutations'
  | 'reactions'
  | 'polls'
  | 'templates'
  | 'presence'
  | 'history_request'
  | 'media'
  | 'edit'
  | 'delete'

export type ConnectorState =
  | 'disconnected'
  | 'connecting'
  | 'pairing'
  | 'connected'
  | 'reconnecting'
  | 'conflict_wait'
  | 'degraded'
  | 'stale'
  | 'logged_out'

export interface ConnectorHealth {
  state: ConnectorState
  lastEventAt: Date | null
  lastInboundAt: Date | null
  lastErrorKind: string | null
  decryptFailures: number
  libraryVersion: string
  phoneLastSeenAt?: Date | null
}

export type SendCommand =
  | { kind: 'send_message'; chatId: string; text: string; quotedProviderId?: string; mentions?: string[] }
  | { kind: 'react_to_message'; chatId: string; providerId: string; emoji: string | null }
  | { kind: 'mark_read'; chatId: string; providerIds: string[] }
  | { kind: 'set_typing'; chatId: string; typing: boolean }

export interface SendResult {
  outcome: 'accepted' | 'rejected'
  /** True once bytes were handed to the transport. Only `false` permits a retry (PRD FR-X2). */
  frameWritten: boolean
  error?: { kind: string; message: string }
}

export interface HistoryRequestHandle {
  requestId: string
}

export interface ChatSnapshotEntry {
  chatId: string
  lastMessageId?: string
  lastMessageAt?: Date
}

export type RawEventHandler = (e: RawEvent) => Promise<void>

/** PRD §6 connector contract. */
export interface Connector {
  readonly accountId: string
  readonly capabilities: ReadonlySet<Capability>
  start(): Promise<void>
  stop(): Promise<void>
  /** Exactly one handler. The connector awaits it before the next event from the same chat. */
  onEvent(handler: RawEventHandler): void
  /** messageId is pre-generated by the executor and used on the wire. */
  send(cmd: SendCommand & { messageId: string }): Promise<SendResult>
  requestHistory(
    chatId: string,
    beforeProviderId: string | null,
    limit: number,
  ): Promise<HistoryRequestHandle>
  listChatsSnapshot(): Promise<ChatSnapshotEntry[]>
  health(): ConnectorHealth
}
